library(readr)
StudentsPerformance <- read_csv("C:/Users/padmaja/OneDrive/Documents/StudentsPerformance/data_raw/StudentsPerformance.csv")
View(StudentsPerformance)
attach(StudentsPerformance)
counts <- c(group1=9,group2=10,group3=6,group4=8,group5=6)
boxplot(counts, main="StudentsPerformance",col="Green")
